# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.answer_options import AnswerOptions  # noqa: F401,E501
from swagger_server import util


class Answer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, text: str=None, options: List[AnswerOptions]=None, answers: Object=None):  # noqa: E501
        """Answer - a model defined in Swagger

        :param type: The type of this Answer.  # noqa: E501
        :type type: str
        :param text: The text of this Answer.  # noqa: E501
        :type text: str
        :param options: The options of this Answer.  # noqa: E501
        :type options: List[AnswerOptions]
        :param answers: The answers of this Answer.  # noqa: E501
        :type answers: Object
        """
        self.swagger_types = {
            'type': str,
            'text': str,
            'options': List[AnswerOptions],
            'answers': Object
        }

        self.attribute_map = {
            'type': 'type',
            'text': 'text',
            'options': 'options',
            'answers': 'answers'
        }
        self._type = type
        self._text = text
        self._options = options
        self._answers = answers

    @classmethod
    def from_dict(cls, dikt) -> 'Answer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Answer of this Answer.  # noqa: E501
        :rtype: Answer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Answer.


        :return: The type of this Answer.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Answer.


        :param type: The type of this Answer.
        :type type: str
        """

        self._type = type

    @property
    def text(self) -> str:
        """Gets the text of this Answer.


        :return: The text of this Answer.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Answer.


        :param text: The text of this Answer.
        :type text: str
        """

        self._text = text

    @property
    def options(self) -> List[AnswerOptions]:
        """Gets the options of this Answer.


        :return: The options of this Answer.
        :rtype: List[AnswerOptions]
        """
        return self._options

    @options.setter
    def options(self, options: List[AnswerOptions]):
        """Sets the options of this Answer.


        :param options: The options of this Answer.
        :type options: List[AnswerOptions]
        """

        self._options = options

    @property
    def answers(self) -> Object:
        """Gets the answers of this Answer.


        :return: The answers of this Answer.
        :rtype: Object
        """
        return self._answers

    @answers.setter
    def answers(self, answers: Object):
        """Sets the answers of this Answer.


        :param answers: The answers of this Answer.
        :type answers: Object
        """

        self._answers = answers
