# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AnswerQueryMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, responses: int=None):  # noqa: E501
        """AnswerQueryMeta - a model defined in Swagger

        :param name: The name of this AnswerQueryMeta.  # noqa: E501
        :type name: str
        :param responses: The responses of this AnswerQueryMeta.  # noqa: E501
        :type responses: int
        """
        self.swagger_types = {
            'name': str,
            'responses': int
        }

        self.attribute_map = {
            'name': 'name',
            'responses': 'responses'
        }
        self._name = name
        self._responses = responses

    @classmethod
    def from_dict(cls, dikt) -> 'AnswerQueryMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnswerQueryMeta of this AnswerQueryMeta.  # noqa: E501
        :rtype: AnswerQueryMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AnswerQueryMeta.


        :return: The name of this AnswerQueryMeta.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AnswerQueryMeta.


        :param name: The name of this AnswerQueryMeta.
        :type name: str
        """

        self._name = name

    @property
    def responses(self) -> int:
        """Gets the responses of this AnswerQueryMeta.


        :return: The responses of this AnswerQueryMeta.
        :rtype: int
        """
        return self._responses

    @responses.setter
    def responses(self, responses: int):
        """Sets the responses of this AnswerQueryMeta.


        :param responses: The responses of this AnswerQueryMeta.
        :type responses: int
        """

        self._responses = responses
