# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.answer import Answer  # noqa: F401,E501
from swagger_server.models.answer_meta import AnswerMeta  # noqa: F401,E501
from swagger_server import util


class FormAnswerBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[Answer]=None, meta_data: AnswerMeta=None):  # noqa: E501
        """FormAnswerBody - a model defined in Swagger

        :param data: The data of this FormAnswerBody.  # noqa: E501
        :type data: List[Answer]
        :param meta_data: The meta_data of this FormAnswerBody.  # noqa: E501
        :type meta_data: AnswerMeta
        """
        self.swagger_types = {
            'data': List[Answer],
            'meta_data': AnswerMeta
        }

        self.attribute_map = {
            'data': 'data',
            'meta_data': 'metaData'
        }
        self._data = data
        self._meta_data = meta_data

    @classmethod
    def from_dict(cls, dikt) -> 'FormAnswerBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The form_answer_body of this FormAnswerBody.  # noqa: E501
        :rtype: FormAnswerBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Answer]:
        """Gets the data of this FormAnswerBody.


        :return: The data of this FormAnswerBody.
        :rtype: List[Answer]
        """
        return self._data

    @data.setter
    def data(self, data: List[Answer]):
        """Sets the data of this FormAnswerBody.


        :param data: The data of this FormAnswerBody.
        :type data: List[Answer]
        """

        self._data = data

    @property
    def meta_data(self) -> AnswerMeta:
        """Gets the meta_data of this FormAnswerBody.


        :return: The meta_data of this FormAnswerBody.
        :rtype: AnswerMeta
        """
        return self._meta_data

    @meta_data.setter
    def meta_data(self, meta_data: AnswerMeta):
        """Sets the meta_data of this FormAnswerBody.


        :param meta_data: The meta_data of this FormAnswerBody.
        :type meta_data: AnswerMeta
        """

        self._meta_data = meta_data
