# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FormOptions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, option: str=None):  # noqa: E501
        """FormOptions - a model defined in Swagger

        :param option: The option of this FormOptions.  # noqa: E501
        :type option: str
        """
        self.swagger_types = {
            'option': str
        }

        self.attribute_map = {
            'option': 'option'
        }
        self._option = option

    @classmethod
    def from_dict(cls, dikt) -> 'FormOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Form_options of this FormOptions.  # noqa: E501
        :rtype: FormOptions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def option(self) -> str:
        """Gets the option of this FormOptions.


        :return: The option of this FormOptions.
        :rtype: str
        """
        return self._option

    @option.setter
    def option(self, option: str):
        """Sets the option of this FormOptions.


        :param option: The option of this FormOptions.
        :type option: str
        """

        self._option = option
