# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.answer_query import AnswerQuery  # noqa: F401,E501
from swagger_server.models.answer_query_meta import AnswerQueryMeta  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[AnswerQuery]=None, meta_data: AnswerQueryMeta=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: List[AnswerQuery]
        :param meta_data: The meta_data of this InlineResponse200.  # noqa: E501
        :type meta_data: AnswerQueryMeta
        """
        self.swagger_types = {
            'data': List[AnswerQuery],
            'meta_data': AnswerQueryMeta
        }

        self.attribute_map = {
            'data': 'data',
            'meta_data': 'metaData'
        }
        self._data = data
        self._meta_data = meta_data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[AnswerQuery]:
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: List[AnswerQuery]
        """
        return self._data

    @data.setter
    def data(self, data: List[AnswerQuery]):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: List[AnswerQuery]
        """

        self._data = data

    @property
    def meta_data(self) -> AnswerQueryMeta:
        """Gets the meta_data of this InlineResponse200.


        :return: The meta_data of this InlineResponse200.
        :rtype: AnswerQueryMeta
        """
        return self._meta_data

    @meta_data.setter
    def meta_data(self, meta_data: AnswerQueryMeta):
        """Sets the meta_data of this InlineResponse200.


        :param meta_data: The meta_data of this InlineResponse200.
        :type meta_data: AnswerQueryMeta
        """

        self._meta_data = meta_data
