# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse500(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: str=None, message: str=None):  # noqa: E501
        """InlineResponse500 - a model defined in Swagger

        :param code: The code of this InlineResponse500.  # noqa: E501
        :type code: str
        :param message: The message of this InlineResponse500.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': str,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }
        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse500':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_500 of this InlineResponse500.  # noqa: E501
        :rtype: InlineResponse500
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this InlineResponse500.


        :return: The code of this InlineResponse500.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this InlineResponse500.


        :param code: The code of this InlineResponse500.
        :type code: str
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse500.


        :return: The message of this InlineResponse500.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse500.


        :param message: The message of this InlineResponse500.
        :type message: str
        """

        self._message = message
